### ISSUE TITLE
Default values in inputs_for

### ISSUE THREAD

**Issue by wakproductions** [mikenichols/actionizer#14]
Hey Mike,

What do you think of allowing a default value to be specified in the inputs_for block?

**Comment by wakproductions** [comment]
I think that would enhance the usefulness of it. Because right now let's say you have a class like this:

```ruby
module UrlTools
  class Resolve
    include Actionizer

    inputs_for :call do
      required :url
      optional :cache_to_redis
    end

    def call
      resolve(input.url)
    end

    private

# <code>

  end
end
```

If I want `cache_to_redis` to default to false, how do I do that? Would probably have to write it in somewhere. Allowing inputs_for to specify would increase its usefulness beyond just a documentation:

```ruby
    inputs_for :call do
      required :url
      optional :cache_to_redis, false
    end
```

**Comment by mikenichols** [comment]
I like it. Having default values would certainly be useful. The one issue I see is how a default interacts with the idea of a `required` or `optional` input. Let's say you have this code (using the default keyword to be explicit)
```ruby
inputs_for(:call) do
  required :url, default: 'www.example.com'
  optional :cache_to_redis, default: false
end
```
For the optional 'cache_to_redis` value, now that we have a default, how do we tell the difference between the programmer explicitly passing in what happens to be the default value and passing nothing at all? This may be trivial but it's still something to think about.

More importantly, for the `required` url, does adding a `default` value now make the variable not _actually_ required? Otherwise, what would be the point of having a default value if you always have to pass a value to override it?

I see one of two options: either default values are only allowed on `optional` inputs, or adding a `default` value to a `required` input now makes the input optional. That could be confusing since `required` inputs are now only required _unless_ they have a default. I would prefer only allowing defaults on `optional` inputs, in part because this is how default method arguments work in ruby. Although I can foresee a time when someone makes a case for why they would want to give a `required` input a default value.

**Comment by wakproductions** [comment]
I don't think default values make sense on `required` inputs. It would only apply to `optional` inputs. I would note this in the documentation.

**Comment by wakproductions** [comment]
I've been thinking about this and planned to write a pull request, but it got me thinking maybe the best practice for defaults is to write methods. Here's an example class and the design pattern I'm really starting to like:

```ruby
module Extractor
  class ProcessDomainList
    include Actionizer

    inputs_for :call do
      optional :offset
      optional :output_stream
    end

    def call
      output.result = list.map do |domain|
        puts "Processing domain: #{domain}"
        {
          "#{domain}" => Extractor::ExtractDomainPages.(domain: domain, output_stream: output_stream).result
        }
      end
    end

    private

    def list
      CommonCrawlExtractor::DOMAINS_WHITELIST[offset..CommonCrawlExtractor::DOMAINS_WHITELIST.size]
    end

    def offset
      input.offset || 0
    end

    def output_stream
      @output_stream ||= input.output_stream || WARC::OutputStream::STDOUT.new
    end

  end
end
```

I just set the defaults within the methods named after the optional inputs. This encourages consistency and gives you the opportunity to memoize default logic. What do you think?

**Comment by mikenichols** [comment]
I like it. It's a simple solution that solves the problem of default values. It's also totally transparent and doesn't force you leave more conventions; we're just calling methods. 👍
